version: '3.8'

services:
    gateway:
        container_name: '${GATEWAY_SERVICE_NAME}'
        image: nginx:1.19.6-alpine
        restart: always
        depends_on:
            - supportpal
            - supportpal_websockets
        environment:
            WEB_CONTAINER: ${WEB_SERVICE_NAME}
            WS_SERVICE_NAME: ${WS_SERVICE_NAME}
        volumes:
            - ./gateway/nginx-http.conf:/etc/nginx/templates/default.conf.template
            - ./gateway/base.conf:/etc/nginx/templates/base.config.template
            - ./gateway/custom.conf:/etc/nginx/templates/custom.config.template
            - ./gateway/http.types:/etc/nginx/conf.d/http.types
        ports:
            - '${HTTP_REMOTE_PORT}:80'
        networks:
            - supportpal_frontend

    supportpal:
        container_name: '${WEB_SERVICE_NAME}'
        image: 'public.ecr.aws/supportpal/helpdesk:${APP_VERSION}'
        restart: always
        depends_on:
            - db
            - redis
            - meilisearch
        environment:
            REDIS_HOST: ${CACHE_SERVICE_NAME}
            REDIS_PORT: ${REDIS_PORT}
            MAILER_SERVICE_NAME: ${MAILER_SERVICE_NAME}
            WS_SERVICE_NAME: ${WS_SERVICE_NAME}
            MQ_SERVICE_NAME: ${MQ_SERVICE_NAME}
            MEILISEARCH_HOST: ${MEILISEARCH_HOST}
            MEILISEARCH_KEY: ${MEILISEARCH_KEY}
        networks:
            - supportpal_frontend
            - supportpal_backend
        command: ["bash", "/etc/cmd/php-fpm.sh"]

    db:
        container_name: '${DATABASE_SERVICE_NAME}'
        image: mysql:8.0.23
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MYSQL_USER_FILE: /run/secrets/db_user
            MYSQL_PASSWORD_FILE: /run/secrets/db_password
        volumes:
            - supportpal_db:/var/lib/mysql
        networks:
            - supportpal_backend
        secrets:
            - db_user
            - db_password
            - db_root_password

    supportpal_websockets:
        container_name: '${WS_SERVICE_NAME}'
        image: 'public.ecr.aws/supportpal/helpdesk:${APP_VERSION}'
        restart: always
        depends_on:
            - db
            - redis
            - meilisearch
        environment:
            REDIS_HOST: ${CACHE_SERVICE_NAME}
            REDIS_PORT: ${REDIS_PORT}
            MAILER_SERVICE_NAME: ${MAILER_SERVICE_NAME}
            WS_SERVICE_NAME: ${WS_SERVICE_NAME}
            MQ_SERVICE_NAME: ${MQ_SERVICE_NAME}
            MEILISEARCH_HOST: ${MEILISEARCH_HOST}
            MEILISEARCH_KEY: ${MEILISEARCH_KEY}
        networks:
            - supportpal_backend
            - supportpal_frontend
        command: ["bash", "/etc/cmd/sockets.sh"]

    supportpal_mq:
        container_name: '${MQ_SERVICE_NAME}'
        image: 'public.ecr.aws/supportpal/helpdesk:${APP_VERSION}'
        restart: always
        depends_on:
            - db
            - redis
            - meilisearch
        environment:
            REDIS_HOST: ${CACHE_SERVICE_NAME}
            REDIS_PORT: ${REDIS_PORT}
            MAILER_SERVICE_NAME: ${MAILER_SERVICE_NAME}
            WS_SERVICE_NAME: ${WS_SERVICE_NAME}
            MQ_SERVICE_NAME: ${MQ_SERVICE_NAME}
            MEILISEARCH_HOST: ${MEILISEARCH_HOST}
            MEILISEARCH_KEY: ${MEILISEARCH_KEY}
        networks:
            - supportpal_backend
        command: ["bash", "/etc/cmd/queues.sh"]
        stop_grace_period: 60s

    redis:
        container_name: '${CACHE_SERVICE_NAME}'
        restart: always
        image: redis:6.0.9-alpine
        command: redis-server --appendonly yes
        volumes:
            - supportpal_cache:/data
        networks:
            - supportpal_backend

    mailer:
        container_name: ${MAILER_SERVICE_NAME}
        image: namshi/smtp
        restart: always
        networks:
            - supportpal_backend

    meilisearch:
        container_name: ${MEILISEARCH_SERVICE_NAME}
        image: getmeili/meilisearch:v1.3.1
        environment:
            MEILI_ENV: ${MEILI_ENV}
            MEILI_LOG_LEVEL: ${MEILI_LOG_LEVEL}
            MEILI_SCHEDULE_SNAPSHOT: ${MEILI_SCHEDULE_SNAPSHOT}
            MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
        volumes:
            - supportpal_meilisearch:/meili_data
        networks:
            - supportpal_backend

volumes:
    supportpal_db:
        external: true
        name: ${DB_VOLUME}
    supportpal_cache:
        external: true
        name: ${CACHE_VOLUME}
    supportpal_meilisearch:
        external: true
        name: ${MEILISEARCH_VOLUME}

networks:
    supportpal_frontend:
        name: ${FRONTEND_NETWORK}
    supportpal_backend:
        name: ${BACKEND_NETWORK}

secrets:
    db_user:
        file: '${SECRETS_DIR}/db_user.txt'
    db_password:
        file: '${SECRETS_DIR}/db_password.txt'
    db_root_password:
        file: '${SECRETS_DIR}/db_root_password.txt'
