version: '3.8'

services:
    gateway:
        environment:
            DOMAIN_NAME: 'example.com'

#  Uncomment services to make changes.
#    supportpal:
#
#    supportpal_websockets:
#
#    supportpal_cron:

