name: docker compose install

on:
    pull_request:

jobs:
    docker_compose_tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Shellcheck
              run: |
                docker run --rm \
                  -v "${PWD}:/v"  \
                  -w "/v" \
                  koalaman/shellcheck \
                  -e SC1091 -e SC1117 \
                  setup.sh
              working-directory: templates/docker-compose
            - name: self-managed
              run: cp templates/docker-compose/.env.dist templates/docker-compose/.env && docker-compose -f templates/docker-compose/docker-compose.yml.dist -f templates/docker-compose/docker-compose.prod.yml.dist -f templates/docker-compose/docker-compose.override.yml.dist config
            - name: Single
              run: docker-compose -f templates/aws/eb/Single/docker-compose.yml.dist -f templates/aws/eb/Single/docker-compose.override.yml.dist config
            - name: Preview
              run: docker-compose -f templates/aws/eb/Preview/docker-compose.yml.dist -f templates/aws/eb/Preview/docker-compose.override.yml.dist config
            - name: HA-web
              run: docker-compose -f templates/aws/eb/HA/web/docker-compose.yml.dist config
            - name: HA-cron
              run: docker-compose -f templates/aws/eb/HA/cron/docker-compose.yml.dist config
