name: linux install

on:
  pull_request:
    paths:
      - templates/linux/**/*

defaults:
  run:
    working-directory: ./templates/linux

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        os:
          - centos:7
          - centos:8
          - ubuntu:18.04
          - ubuntu:20.04
          - debian:9
          - debian:10

    steps:
      - uses: actions/checkout@v2
      - name: Shellcheck
        run: make shellcheck
      - name: Check distribution
        run: TEST_IMAGE=${{ matrix.os }} make test