name: linux install

on:
  pull_request:
    paths:
      - .github/workflows/linux-verify.yml
      - templates/linux/**/*
  schedule:
    - cron:  '0 0 * * *' # Midnight - every night

defaults:
  run:
    working-directory: ./templates/linux

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        os:
          - quay.io/centos/centos:stream8
          - ubuntu:18.04
          - ubuntu:20.04
          - debian:10
          - debian:11

    steps:
      - uses: actions/checkout@v3
      - name: Shellcheck
        run: make shellcheck
      - name: Check distribution
        run: TEST_IMAGE=${{ matrix.os }} make test
