name: linux install

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: ./templates/linux

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        os:
          - centos:7
          - centos:8
          - ubuntu:18.04
          - ubuntu:20.04
          - debian:9
          - debian:10
          - registry.redhat.io/rhel7:7.9
          - registry.access.redhat.com/ubi8/ubi:8

    steps:
      - uses: actions/checkout@v2
      - name: Shellcheck
        run: make shellcheck
      - name: Check distribution
        run: TEST_IMAGE=${{ matrix.os }} make test